docker run centos-cmd echo hello edwardsbeanFROM hypriot/rpi-alpine-scratch 
MAINTAINER rzg <134161558@qq.com>

USER root
WORKDIR /xware
ADD EmbedThunderManager /xware
ADD ETMDaemon /xware
ADD portal /xware
ADD vod_httpserver /xware

ADD monitor.sh /xware
RUN chmod 755 /xware/monitor.sh
RUN chmod 755 /xware/portal


VOLUME /data

EXPOSE 9000

CMD ["./monitor.sh"]
